language: node_js

jobs:
  include:
    - stage: release
      node_js: lts/*
      script: npm run build
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release

branches:
  only:
    - master
  except:
    - /^v\d+\.\d+\.\d+$/